#!/usr/bin/env Rscript

# ============================================================
# Plot species-level CRE turnover and PGLS climate estimates
#
# Panel A:
#   Observed species-level turnover rates by climatic zone.
#
# Panel B:
#   Phylogenetically adjusted PGLS estimates with 95% CI.
#
# Statistical results are generated by
# 02_test_turnover_by_climate.R and are not recalculated here.
#
# Input/output paths are supplied by the climate-analysis
# configuration via the pipeline wrapper.
# ============================================================


# ============================================================
# Arguments
# ============================================================

args <- commandArgs(trailingOnly = TRUE)

get_arg <- function(name) {
    position <- match(name, args)

    if (is.na(position) || position == length(args)) {
        stop("Missing required argument: ", name)
    }

    args[position + 1]
}

INPUT_FILE <- get_arg("--input")
PREDICTIONS_FILE <- get_arg("--predictions")
STATS_FILE <- get_arg("--stats")
OUT_PNG <- get_arg("--out-png")
OUT_PDF <- get_arg("--out-pdf")


# ============================================================
# Input checks
# ============================================================

for (path in c(INPUT_FILE, PREDICTIONS_FILE, STATS_FILE)) {
    if (!file.exists(path)) {
        stop("Required file not found: ", path)
    }
}

dir.create(dirname(OUT_PNG), recursive = TRUE, showWarnings = FALSE)
dir.create(dirname(OUT_PDF), recursive = TRUE, showWarnings = FALSE)


# ============================================================
# Plot settings
# ============================================================

CLIMATE_ORDER <- c("TROP", "ARID", "TEMP", "BORE")

CLIMATE_LABELS <- c(
    TROP = "Tropical",
    ARID = "Arid",
    TEMP = "Temperate",
    BORE = "Boreal"
)

CLIMATE_COLORS <- c(
    TROP = "#E41A1C",
    ARID = "#FBC02D",
    TEMP = "#009E73",
    BORE = "#0072B2"
)


# ============================================================
# Load data
# ============================================================

dat <- read.delim(
    INPUT_FILE,
    stringsAsFactors = FALSE,
    check.names = FALSE
)

pred <- read.delim(
    PREDICTIONS_FILE,
    stringsAsFactors = FALSE,
    check.names = FALSE
)

stats <- read.delim(
    STATS_FILE,
    stringsAsFactors = FALSE,
    check.names = FALSE
)

required_data <- c(
    "climatic_zone",
    "turnover_rate_evaluable"
)

required_pred <- c(
    "climatic_zone",
    "estimate",
    "ci95_low",
    "ci95_high"
)

required_stats <- c(
    "pagel_lambda",
    "p_global"
)

missing <- setdiff(required_data, names(dat))
if (length(missing) > 0) {
    stop("Missing data columns: ", paste(missing, collapse = ", "))
}

missing <- setdiff(required_pred, names(pred))
if (length(missing) > 0) {
    stop("Missing prediction columns: ", paste(missing, collapse = ", "))
}

missing <- setdiff(required_stats, names(stats))
if (length(missing) > 0) {
    stop("Missing stats columns: ", paste(missing, collapse = ", "))
}


# ============================================================
# Prepare data
# ============================================================

dat$climatic_zone <- factor(
    dat$climatic_zone,
    levels = CLIMATE_ORDER
)

pred <- pred[
    match(CLIMATE_ORDER, pred$climatic_zone),
]

if (anyNA(pred$climatic_zone)) {
    stop("Missing climatic zones in PGLS prediction table.")
}

p_global <- as.numeric(stats$p_global[1])
lambda <- as.numeric(stats$pagel_lambda[1])


# ============================================================
# Helpers
# ============================================================

make_fill <- function(colors, alpha = 0.28) {
    grDevices::adjustcolor(colors, alpha.f = alpha)
}


# ============================================================
# Drawing function
# ============================================================

draw_figure <- function() {

    layout(
        matrix(c(1, 2), nrow = 1),
        widths = c(1.18, 1.0)
    )


    # ========================================================
    # Panel A: observed species-level turnover
    # ========================================================

    par(mar = c(5.4, 5.6, 3.4, 1.5))

    y <- dat$turnover_rate_evaluable * 100
    grouped_values <- split(y, dat$climatic_zone)

    boxplot(
        grouped_values,
        outline = FALSE,
        xaxt = "n",
        col = make_fill(CLIMATE_COLORS[CLIMATE_ORDER]),
        border = "#666666",
        ylab = "Turnover candidates among evaluable CRE loci (%)",
        xlab = "Climatic zone",
        las = 1,
        frame.plot = TRUE
    )

    axis(
        1,
        at = seq_along(CLIMATE_ORDER),
        labels = CLIMATE_LABELS[CLIMATE_ORDER]
    )

    # Deterministic offsets are used instead of random jitter so
    # the figure is identical across runs.
    for (i in seq_along(CLIMATE_ORDER)) {
        zone <- CLIMATE_ORDER[i]

        values <- dat$turnover_rate_evaluable[
            dat$climatic_zone == zone
        ] * 100

        if (length(values) == 0) {
            next
        }

        if (length(values) == 1) {
            x <- i
        } else {
            x <- i + seq(-0.10, 0.10, length.out = length(values))
        }

        points(
            x,
            values,
            pch = 21,
            bg = grDevices::adjustcolor(
                CLIMATE_COLORS[zone],
                alpha.f = 0.90
            ),
            col = "#222222",
            cex = 0.85,
            lwd = 0.7
        )
    }

    title(
        main = "Observed species-level turnover",
        line = 1.0,
        font.main = 2
    )

    mtext(
        "A",
        side = 3,
        adj = -0.10,
        line = 2.0,
        font = 2,
        cex = 1.6
    )


    # ========================================================
    # Panel B: PGLS-adjusted estimates
    # ========================================================

    par(mar = c(5.4, 5.0, 3.4, 1.5))

    estimate <- pred$estimate * 100
    lower <- pred$ci95_low * 100
    upper <- pred$ci95_high * 100

    ylim <- range(c(lower, upper), finite = TRUE)
    ylim <- ylim + c(-2.5, 2.5)

    plot(
        seq_along(CLIMATE_ORDER),
        estimate,
        type = "n",
        xaxt = "n",
        xlab = "Climatic zone",
        ylab = "Phylogenetically adjusted turnover rate (%)",
        ylim = ylim,
        las = 1
    )

    axis(
        1,
        at = seq_along(CLIMATE_ORDER),
        labels = CLIMATE_LABELS[CLIMATE_ORDER]
    )

    segments(
        x0 = seq_along(CLIMATE_ORDER),
        y0 = lower,
        x1 = seq_along(CLIMATE_ORDER),
        y1 = upper,
        col = "#222222",
        lwd = 1.4
    )

    segments(
        x0 = seq_along(CLIMATE_ORDER) - 0.07,
        y0 = lower,
        x1 = seq_along(CLIMATE_ORDER) + 0.07,
        y1 = lower,
        col = "#222222",
        lwd = 1.4
    )

    segments(
        x0 = seq_along(CLIMATE_ORDER) - 0.07,
        y0 = upper,
        x1 = seq_along(CLIMATE_ORDER) + 0.07,
        y1 = upper,
        col = "#222222",
        lwd = 1.4
    )

    points(
        seq_along(CLIMATE_ORDER),
        estimate,
        pch = 21,
        bg = CLIMATE_COLORS[CLIMATE_ORDER],
        col = "#222222",
        cex = 1.4,
        lwd = 0.8
    )

    title(
        main = "Phylogenetically adjusted estimates",
        line = 1.0,
        font.main = 2
    )

    mtext(
        "B",
        side = 3,
        adj = -0.02,
        line = 2.0,
        font = 2,
        cex = 1.6
    )

    legend(
        "topright",
        legend = c(
            sprintf("PGLS: p = %.3f", p_global),
            sprintf("Pagel's lambda = %.3f", lambda)
        ),
        bty = "n",
        cex = 0.92,
        inset = c(0, 0.02)
    )
}


# ============================================================
# Save
# ============================================================

png(
    OUT_PNG,
    width = 3360,
    height = 1680,
    res = 300
)

draw_figure()
dev.off()


pdf(
    OUT_PDF,
    width = 11.2,
    height = 5.6
)

draw_figure()
dev.off()


cat(
    "\nWrote:\n",
    OUT_PNG, "\n",
    OUT_PDF, "\n",
    sep = ""
)
